//
//  Activity.swift
//  laBulleVerte
//
//  Created by Apprenant 43 on 29/06/2023.
//

import Foundation

struct Activity: Identifiable {
    var id = UUID()
    var title: String
    var category: String
    var image: String
    var address: String
    var location: Location
    var date: String
    var time: String
    var duration: String
    var participantNumber: Int
    var participant: [String]
    var cost: String
    var about: String
    var charity: String
    var url: String
}

var activities = [
    Activity(title: "Confection de couches pour bébé", category: "creatif", image: "creatif", address: "MJC Pont des Demoiselles, 63bis avenue St Exupéry, 31400 Toulouse", location: locations[0], date: "28 Juin", time: "14h30", duration: "2h30", participantNumber: 12, participant: [""], cost: "10", about: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", charity: "Pro-portion", url: "https://www.pro-portion.fr"),
    Activity(title: "Upcyclage de chutes de tissu", category: "creatif", image: "creatif", address: "La Maison, 16bis Chemin de Mange Pomme, 31520 Ramonville", location: locations[1], date: "29 Juin", time: "15h00", duration: "2h", participantNumber: 15, participant: ["String"], cost: "Gratuit", about: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", charity: "Mission Zéro Déchet", url: "https://zerowastetoulouse.org/qui-sommes-nous/"),
    Activity(title: "Fabrication de jardinières", category: "tool", image: "bricolage", address: "CPIE Terres Toulousaines, 10 rue d'Arcachon, 31200 Toulouse", location: locations[2], date: "30 Juin", time: "18h", duration: "2h", participantNumber: 25, participant: [""], cost: "Gratuit", about: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", charity: "CPIE Terres Toulousaines", url: "http://cpieterrestoulousaines.org"),
    Activity(title: "Construction de nichoir à chauve-souris",category: "tool", image: "bricolage", address: "Jardin pédagogique de Negreneys, 100 rue de Négreneys, 31200 Toulouse", location: locations[3], date: "3 Juillet", time: "14h30", duration: "2h30", participantNumber: 10, participant: [""], cost: "10", about: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", charity: "Les Petits Débrouillards Occitanie", url: "https://www.lespetitsdebrouillardsoccitanie.org"),
    Activity(title: "Fabrication de cosmétiques", category: "diy", image: "diy", address: "Jardin Tourn'Sol, 3' route de Tarbes, 31170 Tournefeuille", location: locations[4], date: "7 Juillet", time: "14h", duration: "3h", participantNumber: 12, participant: [""], cost: "5", about: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", charity: "Les Jardiniers de Tournefeuille", url: "https://www.jardiniersdetournefeuille.org/jardiniers-de-Tournefeuille/gestion-écologique-sur-les-jardins-tournsol"),
    Activity(title: "Fabrication de produits ménagers", category: "diy", image: "diy", address: "MJC Jacques Prévert, 292 Route de Seysses, 31100 Toulouse", location: locations[5], date: "4 Juillet", time: "16h", duration: "2h", participantNumber: 14, participant: [""], cost: "2", about: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", charity: "Zero Waste Toulouse", url: "https://zerowastetoulouse.org/qui-sommes-nous/"),
    Activity(title: "Découvrez la traite des vaches", category: "ferme", image: "ferme", address: "Ferme Pédagogique de Cinquante, Chemin de Mange Pommes, 31520 Ramonville-Saint-Agne", location: locations[6], date: "29 Juin", time: "10h", duration: "2h30", participantNumber: 8, participant: [""], cost: "Gratuit", about: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", charity: "Ferme de Cinquante", url: "https://ferme50.org"),
    Activity(title: "Découvrez la tonte des moutons", category: "ferme", image: "ferme", address: "Ferme Habitat Solidaire, 17 Chemin du Manel, 31400 Toulouse", location: locations[7], date: "3 Juillet", time: "Toute la journée", duration: "Toute la journée", participantNumber: 50, participant: [""], cost: "Gratuit", about: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", charity: "Ferme Habitat Solidaire", url: "https://www.ferme-solidaire.fr"),
    Activity(title: "Semons nos quartiers !", category: "jardin", image: "jardin", address: "Jardin Michoun, Métro roseraie, 31500 Toulouse", location: locations[8], date: "4 Juillet", time: "17h", duration: "1h30", participantNumber: 30, participant: [""], cost: "Gratuit", about: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", charity: "Pro-portion", url: "https://www.pro-portion.fr"),
    Activity(title: "Accueillir des auxiliaires au jardin", category: "jardin", image: "jardin", address: "Parc Monlong, 9 chemin de Perpignan, 31100 Toulouse", location: locations[9], date: "2 Juillet", time: "10h", duration: "2h", participantNumber: 14, participant: [""], cost: "Gratuit", about: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", charity: "Partageons-les jardins", url: "http://partageonslesjardins.fr"),
    Activity(title: "Observation des oiseaux", category: "bio", image: "bio", address: "Le Bazacle, 11 Quai Saint-Pierre, 31000 Toulouse", location: locations[10], date: "2 Juillet", time: "7h", duration: "2h30", participantNumber: 6, participant: [""], cost: "Gratuit", about: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", charity: "LPO Occitanie", url: "https://occitanie.lpo.fr"),
    Activity(title: "Balade botanique", category: "bio", image: "bio", address: "Parc du Confluent,Route de Lacroix-Falgarde, 31120 Portet-sur-Garonne", location: locations[11], date: "7 Juillet", time: "14h", duration: "2h30", participantNumber: 16, participant: [""], cost: "Gratuit", about: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", charity: "Partageons les jardins", url: "http://partageonslesjardins.fr"),
    Activity(title: "Les femmes à vélo: moteur d'un renouveau ?", category: "projection", image: "projection", address: "Maison du vélo, 12 Boulevard Bonrepos, 31000 Toulouse", location: locations[12], date: "3 Juillet", time: "19h00", duration: "1h30", participantNumber: 35, participant: [""], cost: "Gratuit", about: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", charity: "La Maison du Vélo", url: "https://www.maisonduvelotoulouse.com"),
    Activity(title: "2040", category: "projection", image: "projection", address: "Astronef, 3 place des avions, 31400 Toulouse", location: locations[13], date: "29 Juin", time: "19h30", duration: "2h00", participantNumber: 25, participant: [""], cost: "Gratuit", about: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", charity: "Zero Waste Toulouse", url: "https://zerowastetoulouse.org/qui-sommes-nous/"),
    Activity(title: "Comment réduire mes déchets au quotidien ?", category: "cafe", image: "cafe", address: "La Fabrique Solidaire des Minimes, 29bis Avenue des Mazades, 31200 Toulouse", location: locations[14], date: "6 Juillet", time: "2h30", duration: "2h", participantNumber: 30, participant: [""], cost: "Gratuit", about: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", charity: "La Fabrique Solidaire des Minimes", url: "https://lafabriquesolidaire.org"),
    Activity(title: "Comment végétaliser le quartier ?", category: "cafe", image: "cafe", address: "CPIE Terres Toulousaines, 10 rue d'Arcachon, 31200 Toulouse", location: locations[15], date: "8 Juillet", time: "18h", duration: "2h00", participantNumber: 30, participant: [""], cost: "Gratuit", about: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", charity: "CPIE Terres Toulousaines", url: "http://cpieterrestoulousaines.org"),
    Activity(title: "Méga-bassines : pourquoi s’y opposer ?", category: "conference", image: "conference", address: "Médiathèque José Cabanis,1 Allées Jacques Chaban-Delmas, 31500 Toulouse", location: locations[16], date: "4 Juillet", time: "15h", duration: "2h00", participantNumber: 30, participant: [""], cost: "Gratuit", about: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", charity: "Humus & Associés", url: "https://www.humusetassocies.org"),
    Activity(title: "Comment sortir de l’éco-anxiété ?", category: "conference", image: "conference", address: "Médiathèque de Rangueil, 19 Rue Claude de Forbin, 31400 Toulouse", location: locations[17], date: "30 Juin", time: "17h30", duration: "2h00", participantNumber: 30, participant: [""], cost: "Gratuit", about: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", charity: "Humus & Associés", url: "https://www.humusetassocies.org")
]
